### ISSUE TITLE
multiple item manager thingo

### ISSUE THREAD

**Issue by dalygbarron** [marineorganism/LeagueOfPissII#1]
ok so there has gotta be a thing that can maintain a bunch of different item scene nodes that all basically represent the same item but having been placed into the scene in different ways, and of course only one appears at a time.

I am too tired for this.

uuhhhhhhhh

switch usage is pretty much mandatory. Any other way is just going to be weird as hell. yeah so when you set a switch a certain way the manager detects that there is a change and sets it's sub objects such that the right one is appearing. These sub objects are actual item objects and when you pick one up nothing happens basically. The only thing is that we need to turn that switch off again somehow. turning off the switch is mandatory as it is needed for other game logic.
yeah so in order to do this in an easy manner I will add a signal to items called "item picked up" or whatever and when you pick up the item this triggers and the manager thing now knows and turns off the switch that was telling the world that the item was attached to whatever.
hell yeah

hmm yeah ok that should work I think. I will go through some imaginary test cases to see:::::
:we are at the pipe platform and the hook can be attached to stuff. when we enter this area without the item, it should be in the default position, which happens by default when no switches are going and the level has just started. we then pick up this item, and have it in our inventory, but no switches are turned off because this is the default. We then attach it to the boat which turns on the hookOnBoat switch, then we pick it up again which turns off that switch and puts the item back in our inventory. we then go to another level and the item is magically removed, then we come back to the first ldvel and since no switches are going it once again appears in the default positino. We then throw it down a hole and go to another level to see it appear. the hookDownHole switch is on from throwing it down the hole and so the thingo finds that and shows the right item thing. then we pick it up yet again and connect it to a loop thing y in this level which turns off the down hole switch and turns on the connected to loop switch. hmm yeah that sounds ok and in the other level we can also have a loop switch condition to show that it is still down that hole. 

ok hwll yeah all that works. the only problem I have detected is that sometimes you might want the same object to appear for two different switches but tbh I don't really give a fuck, I can just duplicate the objects which would be a hell of a lot easier than doing that shit.

 nicxed

**Comment by dalygbarron** [comment]
yeah so the only thing that really distinguishes this from what I had yesterday is making the item class emit a signal after it's picked up.

**Comment by JoaoBlimping** [comment]
yeet

**Comment by JoaoBlimping** [comment]
hell yeah it works.
Congratulations fellas, we've embraced the divine.

**Comment by JoaoBlimping** [comment]
also had to turn off the self switch thingo though as that was making it stuff up once you were past the first scene
